version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-gatsby-cloud
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-google-gtag
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-plugin-feed
    versions:
    - 3.2.0
